Feature/database
pvl921/MVCalc pull request #2
Opened 2017-05-10 00:26 UTC by pvl921

Внутрь Program.cs добавил запись в базу данных. Записываю флаг результата, операнды, оператор, результат. Время фиксируется в самой БД.

2017-05-10 05:46 UTC, mgrishkov reviewed
См. комменты

2017-05-10 05:46 UTC, mgrishkov commented on src/MVCalc/Program.cs
> +                using (var command = new SqlCommand()) {
Для сокращения можно написать так: var command = new SqlCommand("LogInsert", conn) и выкинуть 2 строки ниже

2017-05-10 05:49 UTC, mgrishkov requested changes

2017-05-10 05:49 UTC, mgrishkov commented on src/MVCalc/Program.cs
> +                using (var conn = new SqlConnection("Server = (local); Database=testDB; User Id=sa; Password=1234;"))
Лучше сделать контроллер и в нем метод записи в лог, чтобы он был тестируемым.

2017-05-10 15:08 UTC, pvl921 commented on src/MVCalc/Program.cs
> +                using (var conn = new SqlConnection("Server = (local); Database=testDB; User Id=sa; Password=1234;"))
Все-таки когда будет правильный лог - когда время фиксируется в контроллере или в БД? Если в БД, то наверное не получится в тесте проверить правильное время в логе, с точностью до секунды.

2017-05-11 05:06 UTC, mgrishkov commented on src/MVCalc/Program.cs
> +                using (var conn = new SqlConnection("Server = (local); Database=testDB; User Id=sa; Password=1234;"))
Правильно будет фиксировать время операции, а не записи, т.е. метка времени должна быть из метода контроллера, но для ознакомительных целей можно и в бд хранить. Причем проблема не столько в точности до долей секунды, сколько в том, что БД ставятся на отдельные серверы, которые могут иметь другой часовой пояс.

2017-05-14 22:17 UTC, pvl921 commented
Добавил методы для чтения всего лога, чтения и удаления отдельной записи по ID.
Запись в базу и удаление из базы занес в контроллер.
Вывод на экран лога (всего и одной записи по ID) оставил пока внутри Program.cs, потому что они связаны с View.
Попробовал добавить тест на работы с БД: создать запись, прочитать ее и удалить после этого.

2017-05-15 06:00 UTC, mgrishkov requested changes

2017-05-15 06:00 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +LogDateTime datetimeoffset
Зачем тут datetimeoffset ? И раз уж ты его используешь, то вопрос на засыпку, какая точность будет при таком объявлении?

2017-05-15 06:00 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +    DROP PROCEDURE dbo.LogView;
Мы делим ХП на Get, List, Add, Delete и Update ну и всякие вариации на тему. Get - всегда возвращает одну запись, List - список

2017-05-15 06:00 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
>  ID int NOT NULL PRIMARY KEY IDENTITY,
Хорошим тоном является именовать констрэйнты в таблицах. 
Первичный ключ PK#ИмяТаблицы@КлюччевоеПоле1@КлючевоеПоле2...
Внешние ключи: FK#ТаблицаКотораяСсылается@Поле1@Поле2#ТаблицаНаКоторуюСсылается@КлючевоеПоле1@КлючевоеПОле2...

2017-05-15 06:00 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
>  AS
всегда заключай тело процедуры в begin ... end

2017-05-15 06:00 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +VALUES (@pResult, CAST(@pDate AS datetimeoffset));
Зачем тут каст?

2017-05-15 06:00 UTC, mgrishkov commented on src/MVCalc/Controllers/LogController.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Блок кода, которые создает подключение и команду, объявляет параметры дублируется в нескольких местах. Придумай, как можно объединить это в одном методе и вызывать его, а не дублировать код.

2017-05-15 06:00 UTC, mgrishkov commented on src/MVCalc/Program.cs
> +        static void DisplayLog()
А почему это не вынес в контроллер работы с БД? Метод возвращает List<...>, ты пробегаешься по нему и вызываешь  View.Render. И да, нужно сделать класс, в который бы являлся представлением результата ХП.

2017-05-15 06:00 UTC, mgrishkov commented on test/BasicTests/BasicTests.csproj
> +    <TargetFramework>netcoreapp1.1</TargetFramework>
Почему произошел downgrade версии?

2017-05-15 06:00 UTC, mgrishkov commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Ой!!!! Это что? Это должен делать контроллер. Ты его тестишь, а не System.Data.SqlClient

2017-05-15 06:00 UTC, mgrishkov commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var command = new SqlCommand($"SELECT * FROM [TEST] WHERE Result = '{testString}'", conn))
Все в контроллер и никаких прямых селеков =)

2017-05-15 06:00 UTC, mgrishkov commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Тоже самое

2017-05-20 08:28 UTC, pvl921 commented on MSSQLDB/testDB_SQLQuery_create_table.sql
>  ID int NOT NULL PRIMARY KEY IDENTITY,
Сделал в виде CONSTRAINT PK#TEST@ID PRIMARY KEY (ID)

2017-05-20 08:31 UTC, pvl921 commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +LogDateTime datetimeoffset
А в чем подвох? На MSDN пишут что точность у datetime2 и datetimeoffset одинакова = 100 нс. Старый datetime не рекомендуют использовать, у него точность 3 мс. 
По-моему, где еще было написано что в новых проектах рекомендуется использовать datetimeoffset, потому что он содержит больше информации.

2017-05-20 08:31 UTC, pvl921 commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +    DROP PROCEDURE dbo.LogView;
Сделал.

2017-05-20 08:31 UTC, pvl921 commented on MSSQLDB/testDB_SQLQuery_create_table.sql
>  AS
Сделал.

2017-05-20 08:32 UTC, pvl921 commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +VALUES (@pResult, CAST(@pDate AS datetimeoffset));
Типы в c# и mssql действительно совпадают, поэтому не нужен. Убрал.

2017-05-20 08:35 UTC, pvl921 commented on src/MVCalc/Controllers/LogController.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Здесь не очень уверен что понял правильно. Вместо 3 строчек сейчас сделал 1 через новый класс GetDBStoredProcedure, в конструкторе которого назначается соединение и ХП. Объявление параметров, передаваемых в ХП, оставил на прежнем месте, потому что они в разных методах разные.

2017-05-20 08:37 UTC, pvl921 commented on src/MVCalc/Program.cs
> +        static void DisplayLog()
Теперь вынес, сделал класс LogModel для представления данных в БД. Засунул его в папку Model. 
Попутно упростил (надеюсь) Program.cs путем вынесения дублирующегося кода в метод ProcessInput.

2017-05-20 08:38 UTC, pvl921 commented on test/BasicTests/BasicTests.csproj
> +    <TargetFramework>netcoreapp1.1</TargetFramework>
Исправил.

2017-05-20 08:40 UTC, pvl921 commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Да, глуповато выглядит. Тестировал базу вместо контроллера. Исправил.
Чтобы в тесте иметь простой доступ к тестовой записи (чтобы удалить ее) изменил ХП Add чтобы она возвращала ID записи.

2017-05-20 08:41 UTC, pvl921 commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var command = new SqlCommand($"SELECT * FROM [TEST] WHERE Result = '{testString}'", conn))
Исправил.

2017-05-20 08:41 UTC, pvl921 commented on test/BasicTests/UnitTests/LogControllerTests.cs
> +            using (var conn = new SqlConnection(Commands.CONNECTION_STRING))
Исправил.

2017-05-20 08:43 UTC, pvl921 commented
Исправил по замечаниям. Посмотри пожалуйста правильно ли понял что нужно было сделать для упрощения кода в LogController.

2017-05-22 08:31 UTC, mgrishkov commented on MSSQLDB/testDB_SQLQuery_create_table.sql
> +LogDateTime datetimeoffset
Подвох в том, что такая точность в 99% не нужна. достаточно (0). А с обычным datetime другая история - у него не ISO диапазон значений 01.01.1753  - 31.12.9999. ISO же требует 01.01.0001-31.12.9999.
По поводу offset - нужно использовать не самые точные типы, а типы, которые удовлетворяют условию задачи. Т.е. ты с каждой записи в пустоту выбрасываешь 2 байта.

2017-05-22 08:42 UTC, mgrishkov reviewed
Небольшой коммент про Dispose

2017-05-22 08:42 UTC, mgrishkov commented on src/MVCalc/Controllers/LogController.cs
> +            public void Dispose ()
Почитай про реализацию этого метода тут
https://msdn.microsoft.com/ru-ru/library/b1yfkh5e%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396

2017-05-29 00:22 UTC, pvl921 commented on src/MVCalc/Controllers/LogController.cs
> +            public void Dispose ()
Добавил стандартную реализацию с Dispose(bool).

2017-05-29 05:54 UTC, mgrishkov approved these changes

2017-05-29 05:54 UTC, merged